CREATE TABLE users(
id SERIAL PRIMARY KEY,
name VARCHAR(100),
email VARCHAR(100) UNIQUE,
password VARCHAR(100)
);

CREATE TABLE jobs(
id SERIAL PRIMARY KEY,
title VARCHAR(100),
company VARCHAR(100),
location VARCHAR(100),
salary VARCHAR(50),
description TEXT
);

CREATE TABLE applications(
id SERIAL PRIMARY KEY,
user_id INT,
job_id INT,
status VARCHAR(20),
applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);